on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: 'README*.md'          
          TOC_TITLE: 'Details'
          FOLDING: 1
          MAX_HEADER_LEVEL: 3
          GITHUB_TOKEN: ${{ github.token }}
